DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT (
    id INT AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(10) NOT NULL,
    lastName VARCHAR(10) NOT NULL
);

DROP TABLE IF EXISTS STUDENT_CLASS;

CREATE TABLE STUDENT_CLASS (
    studentId INT NOT NULL,
    classId INT NOT NULL,
    FOREIGN KEY (studentId) REFERENCES STUDENT(id),
    FOREIGN KEY (classId) REFERENCES CLASS(id)
)

DROP TABLE IF EXISTS CLASS;

CREATE TABLE CLASS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(10) NOT NULL,
);

DROP TABLE IF EXISTS GRADE;

CREATE TABLE GRADE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    score INT NOT NULL,
    FOREIGN KEY (studentId) REFERENCES STUDENT(id),
    FOREIGN KEY (classId) REFERENCES CLASS(id)
);

